Upgrade to `base64-3.5.1` to remove dependency on `bytes`
The 3.5.0 release has a dependency on `bytes` which causes a build error
on OCaml `5.1.0+dev1-2022-06-09`:

```
src_ext/dune-local/dune.exe build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src_ext/base64/src/dune", line 5, characters 12-17:
5 |  (libraries bytes))
                ^^^^^
Error: Library "bytes" not found.
```