archlinux: Always upgrade all the installed packages when installing a new package
e.g. when libc is upgraded and `opam update --depexts && opam install conf-gtksourceview3` is called, pacman will not upgrade the underlying libc and will result in a link failure similar to `undefined reference to 'stat64@GLIBC_2.33'`